import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateFontPreview = async (
  prompt: string, 
  referenceImageBase64?: string,
  previewText: string = "Custom Font",
  bgColor: string = "#ffffff",
  textColor: string = "#1a1a1a",
  fontStyle: string = "normal",
  fontWeight: string = "400"
): Promise<string> => {
  try {
    const parts: any[] = [];

    // 1. Handle Reference Image (Multimodal Input)
    if (referenceImageBase64) {
      let mimeType = 'image/png';
      let base64Data = referenceImageBase64;

      // Extract raw base64 and mime type if strictly provided as Data URL
      if (referenceImageBase64.includes(',')) {
        const [header, data] = referenceImageBase64.split(',');
        base64Data = data;
        const match = header.match(/:(.*?);/);
        if (match) mimeType = match[1];
      }
      
      parts.push({
        inlineData: {
          mimeType,
          data: base64Data
        }
      });
    }

    // 2. Construct Detailed Prompt for Image Generation
    const textPrompt = `Generate a high-quality typographic specimen image of a font based on the following design brief.
    
    DESIGN BRIEF: ${prompt}
    
    RENDER SPECIFICATIONS:
    - Text to display: "${previewText}"
    - Background Color: ${bgColor}
    - Text Color: ${textColor}
    - Font Weight: ${fontWeight}
    - Font Style: ${fontStyle}
    
    REQUIREMENTS:
    - The output must be an IMAGE of text, not a text description.
    - The text "${previewText}" must be centered, clearly legible, and strictly follow the design brief.
    - High contrast, professional vector-like quality.
    - No extra UI elements, just the typography on the requested background color.`;

    parts.push({ text: textPrompt });

    // 3. Call Gemini 2.5 Flash Image (Nano Banana)
    // This model generates the actual pixels of the font specimen.
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts },
    });

    // 4. Extract Generated Image
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }
    }
    
    console.warn("Gemini did not return an image part.");
    throw new Error("No image generated by AI.");

  } catch (error) {
    console.error("Gemini Preview Generation Failed:", error);
    
    // Fallback to placeholder if AI generation fails (e.g. invalid key, quota, etc.)
    const cleanBg = bgColor.replace('#', '');
    const cleanText = textColor.replace('#', '');
    const textToShow = previewText.trim() || "Custom Font";
    return `https://placehold.co/800x400/${cleanBg}/${cleanText}?text=${encodeURIComponent(textToShow)}&font=roboto`;
  }
};